# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GlobalInfo(object):
    def setupUi(self, GlobalInfo):
        GlobalInfo.setObjectName("GlobalInfo")
        GlobalInfo.resize(400, 258)
        self.buttonBox = QtWidgets.QDialogButtonBox(GlobalInfo)
        self.buttonBox.setGeometry(QtCore.QRect(40, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(GlobalInfo)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 20, 261, 55))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_3.addWidget(self.dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.timeEdit = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_2.addWidget(self.timeEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(GlobalInfo)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 100, 361, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoIntersection = QtWidgets.QLineEdit(self.layoutWidget1)
        self.infoIntersection.setObjectName("infoIntersection")
        self.verticalLayout.addWidget(self.infoIntersection)
        self.infoIntersection_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.infoIntersection_3.setObjectName("infoIntersection_3")
        self.verticalLayout.addWidget(self.infoIntersection_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(GlobalInfo)
        self.buttonBox.accepted.connect(GlobalInfo.accept) # type: ignore
        self.buttonBox.rejected.connect(GlobalInfo.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GlobalInfo)

    def retranslateUi(self, GlobalInfo):
        _translate = QtCore.QCoreApplication.translate
        GlobalInfo.setWindowTitle(_translate("GlobalInfo", "Global Info"))
        self.label_5.setText(_translate("GlobalInfo", "Fecha Conteo "))
        self.label_6.setText(_translate("GlobalInfo", "Hora de Inicio (HH:MM)"))
        self.label_2.setText(_translate("GlobalInfo", "Intersección"))
        self.label_3.setText(_translate("GlobalInfo", "Ciudad"))
