# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_projectWindow(object):
    def setupUi(self, projectWindow):
        projectWindow.setObjectName("projectWindow")
        projectWindow.resize(178, 108)
        projectWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Peru))
        self.verticalLayout = QtWidgets.QVBoxLayout(projectWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.projectFormLayout = QtWidgets.QFormLayout()
        self.projectFormLayout.setObjectName("projectFormLayout")
        self.projectNameLabel = QtWidgets.QLabel(projectWindow)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.projectFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.projectNameLabel)
        self.projectNameLineEdit = QtWidgets.QLineEdit(projectWindow)
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.projectFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.projectNameLineEdit)
        self.cityLabel = QtWidgets.QLabel(projectWindow)
        self.cityLabel.setObjectName("cityLabel")
        self.projectFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtWidgets.QLineEdit(projectWindow)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.projectFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cityLineEdit)
        self.verticalLayout.addLayout(self.projectFormLayout)
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        self.loadVideoButton = QtWidgets.QPushButton(projectWindow)
        self.loadVideoButton.setObjectName("loadVideoButton")
        self.buttonsHorizontalLayout.addWidget(self.loadVideoButton)
        self.loadDataButton = QtWidgets.QPushButton(projectWindow)
        self.loadDataButton.setEnabled(False)
        self.loadDataButton.setObjectName("loadDataButton")
        self.buttonsHorizontalLayout.addWidget(self.loadDataButton)
        self.verticalLayout.addLayout(self.buttonsHorizontalLayout)
        self.createProjectButton = QtWidgets.QPushButton(projectWindow)
        self.createProjectButton.setEnabled(False)
        self.createProjectButton.setObjectName("createProjectButton")
        self.verticalLayout.addWidget(self.createProjectButton)

        self.retranslateUi(projectWindow)
        QtCore.QMetaObject.connectSlotsByName(projectWindow)

    def retranslateUi(self, projectWindow):
        _translate = QtCore.QCoreApplication.translate
        projectWindow.setWindowTitle(_translate("projectWindow", "Información del proyecto"))
        self.projectNameLabel.setText(_translate("projectWindow", "Nombre del proyecto"))
        self.cityLabel.setText(_translate("projectWindow", "Ciudad"))
        self.loadVideoButton.setText(_translate("projectWindow", "Cargar video"))
        self.loadDataButton.setText(_translate("projectWindow", "Cargar datos"))
        self.createProjectButton.setText(_translate("projectWindow", "Crear proyecto"))
