# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeWindow(object):
    def setupUi(self, welcomeWindow):
        welcomeWindow.setObjectName("welcomeWindow")
        welcomeWindow.resize(197, 91)
        welcomeWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Peru))
        self.windowVerticalLayout = QtWidgets.QVBoxLayout(welcomeWindow)
        self.windowVerticalLayout.setObjectName("windowVerticalLayout")
        self.welcomeLabel = QtWidgets.QLabel(welcomeWindow)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.windowVerticalLayout.addWidget(self.welcomeLabel, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(welcomeWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.windowVerticalLayout.addWidget(self.line)
        self.descriptionLabel = QtWidgets.QLabel(welcomeWindow)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.windowVerticalLayout.addWidget(self.descriptionLabel)
        self.newProjectButton = QtWidgets.QPushButton(welcomeWindow)
        self.newProjectButton.setObjectName("newProjectButton")
        self.windowVerticalLayout.addWidget(self.newProjectButton)
        self.openProjectButton = QtWidgets.QPushButton(welcomeWindow)
        self.openProjectButton.setObjectName("openProjectButton")
        self.windowVerticalLayout.addWidget(self.openProjectButton)

        self.retranslateUi(welcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(welcomeWindow)

    def retranslateUi(self, welcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        welcomeWindow.setWindowTitle(_translate("welcomeWindow", "FlowVIsionAI v0.0.1"))
        self.welcomeLabel.setText(_translate("welcomeWindow", "<span style=\"font-weight: bold;\">Bienvenido a FlowVisionAI</span>"))
        self.descriptionLabel.setText(_translate("welcomeWindow", "Crea un nuevo proyecto o carga uno existente."))
        self.newProjectButton.setText(_translate("welcomeWindow", "Nuevo proyecto"))
        self.openProjectButton.setText(_translate("welcomeWindow", "Cargar proyecto"))
